# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceships.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10spaceships.proto\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\'\n\x10SpaceshipRequest\x12\x13\n\x0b\x63oordinates\x18\x01 \x01(\t\"\xa2\x01\n\tSpaceship\x12\x1d\n\talignment\x18\x01 \x01(\x0e\x32\n.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\nship_class\x18\x04 \x01(\x0e\x32\x06.Class\x12\x0e\n\x06length\x18\x03 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x1a\n\x08officers\x18\x07 \x03(\x0b\x32\x08.Officer\"5\n\x11SpaceshipResponse\x12 \n\x0crespons_ship\x18\x01 \x03(\x0b\x32\n.Spaceship* \n\tAlignment\x12\x08\n\x04\x41LLY\x10\x00\x12\t\n\x05\x45NEMY\x10\x01*\\\n\x05\x43lass\x12\x0c\n\x08\x43ORVETTE\x10\x00\x12\x0b\n\x07\x46RIGATE\x10\x01\x12\x0b\n\x07\x43RUISER\x10\x02\x12\r\n\tDESTROYER\x10\x03\x12\x0b\n\x07\x43\x41RRIER\x10\x04\x12\x0f\n\x0b\x44READNOUGHT\x10\x05\x32\x44\n\nSpaceships\x12\x36\n\rSendSpaceship\x12\x11.SpaceshipRequest\x1a\x12.SpaceshipResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceships_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALIGNMENT._serialized_start=345
  _ALIGNMENT._serialized_end=377
  _CLASS._serialized_start=379
  _CLASS._serialized_end=471
  _OFFICER._serialized_start=20
  _OFFICER._serialized_end=82
  _SPACESHIPREQUEST._serialized_start=84
  _SPACESHIPREQUEST._serialized_end=123
  _SPACESHIP._serialized_start=126
  _SPACESHIP._serialized_end=288
  _SPACESHIPRESPONSE._serialized_start=290
  _SPACESHIPRESPONSE._serialized_end=343
  _SPACESHIPS._serialized_start=473
  _SPACESHIPS._serialized_end=541
# @@protoc_insertion_point(module_scope)
