# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spaceships_pb2 as spaceships__pb2


class SpaceshipsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSpaceship = channel.unary_unary(
                '/Spaceships/SendSpaceship',
                request_serializer=spaceships__pb2.SpaceshipRequest.SerializeToString,
                response_deserializer=spaceships__pb2.SpaceshipResponse.FromString,
                )


class SpaceshipsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSpaceship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceshipsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSpaceship': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSpaceship,
                    request_deserializer=spaceships__pb2.SpaceshipRequest.FromString,
                    response_serializer=spaceships__pb2.SpaceshipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Spaceships', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Spaceships(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSpaceship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Spaceships/SendSpaceship',
            spaceships__pb2.SpaceshipRequest.SerializeToString,
            spaceships__pb2.SpaceshipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
